<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <RepositoryUrl>https://github.com/brunoryckaert/BlazorSortableList</RepositoryUrl>
    <PackageOutputPath>/Users/Bruno/Documents/dev/packages</PackageOutputPath>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/brunoryckaert/BlazorSortableList</PackageProjectUrl>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Copyright>Burke Holland, Alex Nek</Copyright>
    <Description>An implementation of the SortableJS library for Blazor</Description>
    <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
    <PackageId>BlazorSortableList-fork-attribute_splatting</PackageId>
    <Version>2.3.3</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.MD">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components">
      <Version Condition="'$(TargetFramework)' == 'net8.0'">8.0.11</Version>
      <Version Condition="'$(TargetFramework)' == 'net9.0'">9.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web">
      <Version Condition="'$(TargetFramework)' == 'net8.0'">8.0.11</Version>
      <Version Condition="'$(TargetFramework)' == 'net9.0'">9.0.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Content Update="SortableList.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="sortable-list.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>